List<String> chapterSixList = [
  "General*Principles",
  "Assumptions",
  "Load*Combination and Increase in Permissible Stresses",
  "Design*Spectrum",
];

List<String> chapterSixOneList = [
  "6.1.1*Ground Motion*The characteristics ( intensity, duratio~ etc ) of seismic ground vibrations expected at any location depends upon the magnitude of earthquake, its depth of focus, distance from the epicentre, characteristics of the path through which the seismic waves travel, and the soil strata on which the structure stands. The random earthquake ground motions, which cause the structure to vibrate, can be resolved in any three mutually perpendicular directions.\n   The predominant direction of ground vibration is usually horizontal. Earthquake-generated vertical inertia forces are to be considered in design unless checked and proven by specimen calculations to be not significant. Vertical acceleration should be considered in structures with large spans, those in which stability is a criterion for design, or for overall stability analysis of structures. Reduction in gravity force due to vertical component of ground motions can be particularly detrimental in cases of prestressed horizontal members and of cantilevered members. Hence, special attention should be paid to the effect of vertical component of the ground motion on prestressed or cantilevered beams, girders and slabs.",
  "6.1.2**The response of a structure to ground vibrations is a fimction of the nature of foundation soil, materials, form, size and mode of construction of structures; and the duration and characteristics of ground motion. This standard specifies design forces for structures standing on rocks or soils which do not settle, liquefi or slide due to loss of strength during ground vibrations.",
  "6.1.3**The design approach adopted in this standard is to ensure that structures possess at least a minimum strength to withstand minor earthquakes ( <DBE ), which occur frequently, without damage; resist moderate earthquakes ( DBE ) without significant structural damage though some non-structural damage may OCCUEand aims that structures withstand a major earthquake ( MCE ) without collapse, Actual forces that appear on structures during earthquakes are much greater than the design forces speciiled in this standard. However, ductility, arising from inelastic material behaviourand detailing, and overstrength, arising from the additional reserve strength in structures over and above the design strength, are relied upon to account for this difference in actual and design lateral loads. Reinforced and prestressed concrete members shall be suitably designed to ensure that premature failure due to shear or bond does not occur, subject to the provisions of IS 456 and IS 1343. Provisions for appropriate ductile detailing of reinforced concrete members are given in IS 13920, \n  In steel structures, members and their connections should be so proportioned that high ductility is obtain~ tide SP 6 (Part 6 ), avoiding premature failure due to elastic or inelastic buckling of any type. \n  The specified earthquake loads are based upon postelastic energy dissipation in the structure and because of this fact, the provision of this standard for design, detailing and construction shall be satisfied even for structures and members for which load combinations that do not contain the earthquake effectindicate larger demands than combinations including earthquake.",
  "6.1.4*Soil-Structure Interaction *The soil-structure interaction refers to the effects of the supporting foundation medium on the motion of structure. The soil-structure interaction may not be considered in the seismic analysis for structures supported on rock or rock-like material.",
  "6.1.5**The design lateral force specified in this standard shall be considered in each of the two orthogonal horizontal directions of the structure. For structures which have lateral force resisting elements in the two orthogonal directions only, the design lateral force shall be considered along one direction at a time, and not in both directions simultaneously. Structures, having lateral force resisting elements (for example frames, shear walls ) in directions other than the two orthogonal directions, shall be analysed considering the load combinations specified in 6.3.2. Where both horizontal and vertical seismic forces are taken into account, load combinations specified in 6.3.3 shall be considered.",
  "6.1.6**Equipment and other systems, which are supported at various floor levels of the structure, will be subjected to motions corresponding to vibration at their support points. In important cases, it may be necessary to obtain floor response spectra for design of equipment supports. For detail reference be made to IS 1893 (Part 4).",
  "6.1.7*Additions to Existing Structures*Additions shall be made to existing structures only as follows:\na) An addition that is structurally independent from an existing structures shall be designed and constructed in accordance with the seismic requirements for new structures.\nAn addition that is not structurally independent from an existing structure shall be designed and constructed such that the entire structure conforms to the seismic force resistance requirements for new structures unless the following three conditions are complied with:\n1) The addition shall comply with the requirements for new structures.\n 2) The addition shall notincrease the seismic forces in any structural elements of the existing structure by more than 5 percent unless the capacity of the element subject to the increased force is still in compliance with this standard, and\n3) The additicn shall not decrease the seismic resistance of any structural element of the existing structure unless reduced resistance is equal to or greater than that required for new structures.",
  "6.1.8**Change in Occupancy*When a change of occupancy results in a structure being re-classified to a higher importance factor ( 1 ), the structure shall conform to the seismic requirements for anew structure with the higher importance factor.",
];

List<String> chapterSixTwoList = [
  "6.2.1**The following assumptions shall be made in theearthquake resistant design of structures:",
  "a)**Earthquake causesimpulsive ground motions, which are complex and irregular in character, changing in period and amplitude each lasting for a small duration. Therefore, resonance of the type as visualized under steady-state sinusoidal excitations, will not occur as it would need time to buildup such amplitudes.\nNOTE— However, there are exceptions where resonance-like conditions have been seen to occur between long distance waves and tall structures founded on deep soft soils.",
  "b)**Earthquake is not likely to occur simultaneously with wind or maximum flood or maximum sea waves,",
  "c)**The value of elastic modulus of materials, wherever required, may be taken as for static analysis unless a more definite value is available for use in such condition ( see IS 456, IS 1343 and IS 800 )"
];

List<String> chapterSixThreeList=[
  "Load*Combinations",
  "Design*Horizontal Earthquake Load",
  "Design*Vertical Earthquake Load",
  "Combination*for Two or Three Component Motion",
  "Increase*in Permissible Stresses"
];

List<String> chapterSixThreeOneList=[
  "**When earthquake forces are considered on a structure these shall be combined as per 6.3.1.1 and 6.3.1.2 where the terms DL, IL and EL stand for the response quantities due to dead load, imposed load and designated earthquake load respectively.",
  "6.3.1.1**Load factors for plastic design of steel structures\nIn the plastic design of steel structures, the following load combinations shall be accounted for: \n 1) 1.7(DL +  IL)\n 2) 1.7(DL ± EL)\n 3) 1.7(DL + IL ± EL)",
  "6.3.1.2**Partial safety factors for limit state design of reinforced concrete and prestressed concrete structures\nIn the limit state design of reinforced and prestressed concrete structures, the following load combinations shall be accounted for: \n1) 1.5(DL + IL)\n2) 1.5(DL + IL ± EL)\n3)1.5(DL ± EL)\n4)0.9 DL ± 1.5 EL",
];

List<String> chapterSixThreeTwoList=[
  "6.3.2.1**When the lateral load resisting elements are oriented along orthogonal horizontal direction, the structure shall be designed for the effects due to till design earthquake load in one horizontal direction at time.",
  "6.3.2.2**When the lateral load resisting elements are not oriented along the orthogonal horizontal directions, the stmcture shall be designed for the effects due to foil design earthquake load in one horizontal direction plus 30 percent of the design earthquake load in the other direction.",
];

List<String> chapterSixThreeThreeList=[
  "When effects due to vertical earthquake loads are to be considered, the design vertical force shall be calculated in accordance with 6.4.5",
];

List<String> chapterSixThreeFourList=[
"6.3.4.1**When responses from the three earthquake components are to be considered, the responses due to each component may be combined using the assumption that when the maximum response from one component occurs, the responses from the other two component are 30 percent of their maximum. All possible combinations of the three components ( ELx, ELy and ELz ) including variations in sign ( plus or minus ) shall be considered, Thus, the response due earthquake force (EL ) is the maximum ofthe following three cases: \n1)± ELx ± 0.3 ELy ± 0.3 ELz\n2)± ELy ± 0.3 ELx ± ELz\n3)± ELz ± 0.3 ELx ± 0.3 ELy\nwhere x and y are two orthogonal directions and z is vertical direction", 
"6.3.4.2**As an alternative to the procedure in 6.3.4.1, the response (EL ) due to the combined effect of the three components can be obtained on the basis of ‘square root of the sum of the square ( SRSS )‘ that is ",
"6.3.4.3**When two component motions ( say one horizontal and one vertical, or only two horizontal) are combined, the equations in 6.3.4.1 and 6.3.4.2 should be modified by del >tingthe term representing the response due to the component of motion not being considered."
];

List<String> chapterSixThreeFiveList=[
  "6.3.5.1*Increase impermissible stresses in material*When earthquake forces are considered along with other normal design forces, the permissible stresses in material, in the elastic method of design, maybe increased by one-third. However, for steels having a definite yield stress, the stress be limited to the yield stress; for steels without a definite yield point, the stress will be limited to 80 percent of the ultimate strength or 0.2 percent proof stress, whichever is smaller; and that in prestressed concrete members, the tensile stre’ssin the extreme fibers of the concrete may be permitted so as not to exceed two-thirds of the modulus of rupture of concrete.",
  "6.3.5.2*Increase in allowable pressure in soils*When earthquake forces are included, the allowable bearing pressure in soils shall be increased as per Table 1, depending upon type of foundation of the structure and the type of soil. In soil deposits consisting of submerged loose sands and soils falling under classification SP with standard penetration N-values less than 15 in seismic Zones III, IV, V and less than 10 in seismic Zone II, the vibration caused by earthquake may cause liquefaction or excessive total and differential settlements. Such sites should preferably be avoided while locating new settlements or important projects. Otherwise, this aspect of the problem needs to be investigated and appropriate methods of compaction or stabilization adopted to achieve suitable N-values as indicated in Note 3 under Table 1. Alternatively, deep pile foundation may be provided and taken to depths well into the layer which is not likely to liquefi. Marine clays and other sensitive clays are also known to lique~ due to collapse of soil structure and will need special treatment according to site condition.",
];



List<String> chapterSixFourList=[
  "6.4.1 For the purpose of determining seismic forces, the country is classified into four seismic zones as shown in Fig. 1.",
  "6.4.2 The design horizontal seismic coefficient Ah for a structure shall be determined by the following expression: Ah=ZISa/2Rg\nProvided that for any structure with T ⩽0.1 s, the value of A~will not be taken less than Z/2 whatever be the value of I/R.\nwhere\nZ = Zone factor given in Table 2, is for the Maximum Considered Earthquake ( MCE ) and service life of structure in a zone. The factor 2 in the denominator of Z is used so as to reduce the Maximum Considered Earthquake ( MCE ) zone factor to the fktor for Design Basis Earthquake ( DBE ).\nI = Importance factor, depending upon the functional use of the structures, characterised by.hazardous consequences of its failure, post-earthquake functional needs, historical value, or economic importance ( Table 6 ).\nR = Response reduction factor, depending on the perceived seismic damage performance of the structure, characterised by ductile or brittle deformations. However, the ratio (I/R ) shall not be greater than 1.0( Table7). The values ofR for buildings are given in Table 7.\nSa/g = Average response acceleration coefficient for rock or soil sites as given by Fig. 2 and Table 3 based on appropriate natural periods and damping of the structure. These curves represent free tleld ground motion.",
];
