List<String> chapterFiveList = [
  "1**Design horizontal seismic coefficient.",
  "2**Design horizontal acceleration spectrum value for mode k of vibration.",
  "3**ith Floor plan dimension of the building perpendicular to the direction of force.",
  "4**Index for the closely-spaced modes.",
  "5**Base dimension of the building, in metres, in the direction in which the seismic force is considered.",
  "6**Response quantity due to dead load.",
  "7**Design eccentricity to be used at floor i calculated as per 7.8.2.",
  "8**Static eccentricity at floor i defined as the distance between centre of mass and centre of rigidity.",
  "9**Response quantity due to earthquake load for horizontal shaking along x-direction.",
  "10**Response quantity due to earthquake load for horizontal shaking along y-direction.",
  "11**Response quantity due to earthquake load for vertical shaking along z-direction.",
  "12**Design lateral forces at the roof due to all modes considered.",
  "13**Design lateral forces at the floor i due to all modes considered.",
  "14**Acceleration due to gravity.",
  "15**Height of structure, in metres.",
  "16**Height measured from the base of the building to floor i.",
  "17**Importance factor.",
  "18**Response quantity due to imposed load.",
  "19**Modal mass of mode k.",
  "20**Number of storeys.",
  "21**SPT value for soil.",
  "22**Modal participation factor of mode k.",
  "23**Lateral force at floor i.",
  "24**Design lateral force at floor i in mode k.",
  "25**Number of modes to be considered as per 7.8.4.2.",
  "26**Response reduction factor.",
  "27**Average response acceleration coefficient for rock or soil sites as given by Fig. 2 and Table 3 based on appropriate natural periods and damping of the structure.",
  "28**Undamped natural period of vibration of the structure (in second ).",
  "29**Approximate fundamental period ( in seconds ).",
  "30**Undamped natural period of mode k of vibration (in second ).",
  "31**Fundamental natural period of vibration (in second ).",
  "32**Design seismic base shear.",
  "33**Design base shear calculated using the approximate fimdamental period T.",
  "34**Peak storey shear force in storey i due to all modes considered.",
  "35**Shear force in storey i in mode k.",
  "36**Peak storey shear force at the roof due to all modes considered.",
  "37**Seismic weight of the structure.",
  "38**Seismic weight of floor i.",
  "39**Zone factor.",
  "40**Mode shape coet%cient at floor i in mode k.",
  "41**Peak response (for example member forces, displacements, storey forces, storey shears or base reactions ) due to all modes considered.",
  "42**Absolute value of maximum response in mode k.",
  "43**Absolute value of maximum response in mode c, where mode c is a closely-spaced mode.",
  "44**Peak response due to the closely-spaced modes only.",
  "45**Coefficient used in the Complete Quadratic Combination ( CQC ) method while combining responses of modes i and j.",
  "46**Circular frequency in rad/second in the ith mode.",
];

List<String> symbolList=[
  "A*h",
  "A*k",
  "b*i",
  "c*",
  "d*",
  "DL*",
  "e*di",
  "e*si",
  "EL*x",
  "EL*y",
  "El*z",
  "F*roof",
  "F*i",
  "g*",
  "h*",
  "h*i",
  "I*",
  "IL*",
  "M*k",
  "n*",
  "N*",
  "P*k",
  "Q*i",
  "Q*ik",
  "r*",
  "R*",
  "S*a/g",
  "T*",
  "T*a",
  "T*k",
  "T*I",
  "V*B",
  "V*B",
  "V*i",
  "V*ik",
  "V*roof",
  "W*",
  "W*i",
  "Z*",
  "Φ*ik",
  "λ*",
  "λ*k",
  "λ*c",
  "λ*∗",
  "ρ*ij",
  "ω*i",
];