List<String> chapterTwoList = [
  "1*456:2000*Code of practice for plain and reinforced concrete ( fourth revision ).",
  "2*800:1984*Code of practice for general construction in steel ( second revision ).",
  "3*875*Code of practice for design loads ( other than earthquake ) forbuildings and structures.\n\n(Part l) 1987  Dead loads — Unit weights of building material and storedmaterials ( second revision).\n\n(Part 2):1987  Imposed loads ( second revision).\n(Part 3):1987 Wind loads ( second revision).\n\n(Part4 ):1987 Snow loads ( second revision).\n\n(Part 5):1987  Special loads and load combinations ( second revision).",
  "4*1343:1980*Code of practice for pre-stressed concrete (first revision ).",
  "5*1498:1970*Classification and identification of soils for general engineering  purposes (first revision ).",
  "6*1888:1982*Method of load test on soils (second revision ).",
  "7*1893 (Part4)*Criteria for earthquake resistant design of structures: Part 4 Industrial structures including stack like structures.",
  "8*2131:1981*Method of standard penetration test for soils (first revision ).",
  "9*2809:1972*Glossary of terms and symbols relating to soil engineering ( jirst revision ).",
  "10*2810:1979*Glossary of terms relating to soil dynamics (fzrst revision).",
  "11*4326:1993*Earthquake resistant design and construction of buildings — Code of practice ( second revision ).",
  "12*6403:1981*Code of practice for determination of bearing capacity of shallow foundations (first revision ).",
  "13*13827:1993*Improving earthquake resistance of earthen buildings — Guidelines.",
  "14*13828:1993*Improving earthquake resistance of low strength masonry buildings — Guidelines.",
  "15*13920:1993*Ductile detailing of reinforced concrete structures subjected to  seismic forces — Code of practice.",
  "16*13935:1993*Repair and seismic strengthening of buildings — Guidelines.",
  "17*SP6 ( 6 ) :1972*Handbook for structural engineers:Application of plastic theory in design of steel structures.",
];
