List<String> chapterThreeList = [
  "3.1**For the purpose of this standard, the following definitions shall apply which are applicable generally to all structures.",
  "3.2*Closely-Spaced Modes*Closely-spaced modes of a structure are those of its natural modes of vibration whose natural frequencies differ from each other by 10 percent or less of the lower frequency.",
  "3.3*Critical Damping*The damping beyond which the free vibration motion will not be oscillatory.",
  "3.4*Damping*The effect of internal friction, imperfect elasticity of material, slipping, sliding, etc in reducing the amplitude of vibration and is expressed as a percentage of critical damping.",
  "3.5*Design Acceleration Spectrum*Design acceleration spectrum refers to an average smoothened plot ofmaximum acceleration as a fimction of frequency or time period of vibration for a specitled damping ratio for earthquake excitations at the base of a single degree of freedom system.",
  "3.6*Design Basis Earthquake*It is the earthquake which can reasonably be expected to occur at least once during the design life of the structure",
  "3.7*Design Horizontal Acceleration Coefficient*It is a horizontal acceleration coefficient that shall be used for design of structures.",
  "3.8*Design Lateral Force*It is the horizontal seismic force prescribed by this standard, that shall be used to design a structure.",
  "3.9*Ductility*Ductility of a structure, or its members, is the capacity to undergo large inelastic deformations without significant loss of strength or stiffness.",
  "3.10*Epicentre*Epicentre The geographical point on the surface of earth vertically above the focus of the earthquake.",
  "3.11*Effective Peak Ground Acceleration.*It is O.4 times the 5 percent damped average spectral acceleration between period 0.1 to 0.3 s. This shall be taken as Zero Period Acceleration ( ZPA ).",
  "3.12**Floor Response Spectra*Floor response spectra is the response spectra for a time history motion of a floor. This floor motion time history is obtained by an analysis of multi-storey building for appropriate material damping values subjected to a specified earthquake motion at the base of structure.",
  "3.13*Focus*The originating earthquake source ofthe elastic waves inside the earth which cause shaking of ground due to earthquake.",
  "3.14*Importance Factor*It is a factor used to obtain the design seismic force depending on the functional use of the structure, characterised by hazardous consequences of its failure, its post-earthquake functional need, historic value, or economic importance.",
  "3.15*Intensity of Earthquake*The intensity of an earthquake at a place is a measure of the strength of shaking during the earthquake, and is indicated by a number according to the modified Mercalli Scale or M.S.K. Scale of seismic intensities (see AnnexD ).",
  "3.16*Liquefaction*Liquefaction is a state in saturated cohesionless soil wherein the effective shear strength is reduced to negligible value for all engineering purpose due to pore pressure caused by vibrations during an earthquake when they approach the total confining pressure. In this condition the soil tends to behave like a fluid mass.",
  "3.17*Lithological Features*The nature of the geological formation of the earths crust above bed rock on the basis ofsuch characteristics as colour, structure, mineralogical composition and grain size.",
  "3.18*Magnitude of Earthquak*The magnitude of earthquake is a number, which is a measure of energy released in an earthquake. It is defined as logarithm to the base 10 of the maximum trace amplitude, expressed in microns, which the standard short-period torsion seismometer ( with a period of 0.8s, magnification 2800 and damping nemly critical ) would register due to the earthquake at an epicentral distance of 100 km.",
  "3.19*Maximum Considered Earthquake*The most severe earthquake effects considered by this standard.",
  "3.20*Modal Mass*Modal mass of a structure subjected to horizontal or vertical, as the case maybe, ground motion is apart ofthe total seismic mass of the structure that is effective in mode k of vibration. The modal mass for a given mode has a unique value irrespective of scaling of the mode shape.",
  "3.21*Modal Participation Factor*Modal participation factor of mode k of vibration is the amount by which mode k contributes to the overall vibration of the structure under horizontal and vertical earthquake ground motions. Since the amplitudes of 95 percent mode shapes can be scaled arbitrarily, the value of this factor depends on the scaling used for mode shapes.",
  "3.22**Modes of Vibration ( see Normal Mode).",
  "3.23*Mode Shape Coefficient*When a system is vibrating in normal mode k, at any particular instant of time, the amplitude of mass i expressed as a ratio of the amplitude of one of the masses of the system, is known as mode shape coefficient ( @i~).",
  "3.24*Natural Period*Natural period of a structure is its time period of undamped free vibration.",
  "3.24.1*Fundamental Natural Period*It is the first ( longest ) modal time period of vibration.",
  "3.24.2*Modal Natural Period*The modal natural period of mode k is the time period of vibration in mode k.",
  "3.25**Normal Mode*A system is said to be vibrating in a normal mode when all its masses attain maximum values of displacements and rotations simultaneously, and pass through equilibrium positions simultaneously.",
  "3.26*Response Reduction Factor*It is the factor by which the actual base shear force, that would be generated if the structure were to remain elastic during its response to the Design Basis Earthquake (DBE ) shaking, shall be reduced to obtain the design lateral force.",
  "3.27*Response Spectrum*The representation of the maximum response of idealized single degree freedom systems having certain period and damping, during earthquake ground motion. The maximum response is plotted against the undamped natural period and for various damping values, and can be expressed in terms of maximum absolute acceleration, maximum relative velocity, or maximum relative displacement.",
  "3.28*Seismic Mass*It is the seismic weight divided by acceleration due to gravity.",
  "3.29*Seismic Weight*It is the total dead load plus appropriate amounts of specified imposed load.",
  "3.30*Structural Response Factors*It is a factor denoting the acceleration response spectrum of the structure subjected to earthquake ground vibrations, and depends on natural period of vibration and damping of the structure.",
  "3.31**Tectonic Features*The nature of geological formation of the bedrock in the earth’s crust revealing regions characterized by structural features, such as dislocation, distortion, faults, folding, thrusts, volcanoes with their age of formation, which are directly involved in the earth movement or quake resulting in the above consequences.",
  "3.32*Time History Analysis*It is an analysis ofthe dynamic respmse ofthe structure at each increment of time, when its base is subjected to a specific ground motion time history.",
  "3.33*Zone Factor*It is a factor to obtain the design spectrum depending on the perceived maximum seismic risk characterized by Maximum Considered Earthquake ( MCE ) in the zone in which the structure is located. The basic zone fiwtorsincluded in this standard are reasonable estimate of effective peak ground acceleration.",
  "3.34*Zero Period Acceleration*It is the value of acceleration response spectrum for period below 0.03 s ( frequencies above 33 Hz).",
];
