List<String> chapterFourList = [
  "4.1**For the purpose of earthquake resistant design of buildings in this standard, the following definitions shall apply.",
  "4.2*Base*It is the level at which inertia forces generated in the strnctnre are transferred to the foundatio.",
  "4.3*Base Dimensions*Base dimension of the building along a direction is the dimension at its base, in metre, along that direction.",
  "4.4*Centre of Mass*The point through which the resultant of the masses of a system acts. This point corresponds to the centre of gravity of masses of system.",
  "4.5*Centre of Stiffness*The point through which the resultant of the restoring forces of a system acts.",
  "4.6*Design Eccentricity*It is the value of eccentricity to be used at floor i in torsion calculations for design.",
  "4.7*Design Seismic Base Shear*It is the total design lateral force at the base of a structure.",
  "4.8**Diaphragm*It is a horizontal, or nearly horizontal system, which transmits lateral forcesto the vertical resisting elements, for example, reinforced concrete floors and horizontal bracing systems.",
  "4.9*Dual System*Buildings with dual system consist of shear walls ( or braced frames ) and moment resisting frames such that: (a) The two systems are designed to resist the total design lateral force in proportion to their lateral stiffness considering the interaction of the dual system at all floor levels; and (b) The moment resisting frames are designed to independently resist at least 25 percent of the design base shear.",
  "4.10*Height of Floor*It is the difference in levels between the base of the building and that of floor i.",
  "4.11*Height of Structure*It is the difference in levels, in metres, between its base and its highest level.",
  "4.12*Horizontal Bracing System*It is a horizontal truss system that serves the same function as a diaphragm.",
  "4.13**Joint*It is the portion of the column that is common to other members, for example, beams, framing into it.",
  "4.14*Lateral Force Resisting Element*It is part of the structural system assigned to resist lateral forces.",
  "4.15*Moment-Resisting Frame*It is a frame in which members and joints are capable of resisting forces primarily by flexure.",
  "4.15.1*Ordinary Moment-Resisting Frame*It is a moment-resisting frame not meeting special detailing requirements for ductile behaviour.",
  "4.15.2*Special Moment-Resisting Frame*It is a moment-resisting frame specially detailed to provide ductile behaviour and comply with the requirements given in IS 4326 or IS 13920 or SP6(6).",
  "4.16*Number of Storeys*Number of storeys of a building isthe number of levels above the base. This excludes the basement storeys, where basement walls are connected with the ground floor deck or fitted between the building columns. But, it includes the basement storeys, when they are not so connected.",
  "4.17*Principal Axes*Principal axes of a building are generally two mutually perpendicular horizontal directions inphmof abuilding along which the geometry of the building is oriented.",
  "4.18*P-A Effect*It is the secondary effect on shears and moments of frame members due to action of the vertical loads, interacting with the lateral displacement of building resulting from seismic for~es.",
  "4.19*Shear Wall*It is a wall designed to resist lateral forces acting in its own plane.",
  "4.20*Soft Storey*It is one in which the lateral stiffness is less than 70 percent of that in the storey above or less than 80 percent of the average lateral stiffness of the three storeys above.",
  "4.21*Static Eccentricity*It is the distance between centre of mass and centre of rigidity of floor i.",
  "4.22*Storey*It is the space between two adjacent floors.",
  "4.23*Storey Drift*It is the displacement of one level relative to the other level above or below.",
  "4.24*Storey Shear*It is the sum of design lateral forces at all levels above the storey under consideration.",
  "4.25*Weak Storey*It is one in which the storey lateral strength is less than 80 percent of that in the storey above, The storey lateral strength is the total strength of all seismic force resisting elements sharing the storey shear in the considered direction.",
];
